(() => {
  "use strict";

  window.LucidEditor = window.LucidEditor || {};
  window.LucidEditor.config = {
    EDITOR_VERSION: "0.2.0",
    PROJECT_SCHEMA_VERSION: 2,
    ITEM_SCHEMA_VERSION: 1,
    GRID_SIZE: 32,
    GRID_MAJOR_FACTOR: 4,
    CAMERA_LIMITS: { minZoom: 0.2, maxZoom: 4 },
    HISTORY_LIMIT: 60,
    // Zentrale Uebersicht aller Tastenkuerzel (einzige Quelle der Wahrheit).
    // Werkzeug-Kuerzel stehen zusaetzlich in TOOL_DEFINITIONS[].shortcut und
    // werden daraus abgeleitet, damit sie nicht doppelt gepflegt werden.
    KEYBINDINGS: {
      global: {
        undo: "Ctrl+Z",
        redo: "Ctrl+Y",
      },
      levelEditor: {
        resetZoom: "Ctrl+0",
        playtest: "Ctrl+Enter",
        deleteSelection: "Delete",
        neutral: "Esc",
      },
    },
    DEFAULT_PROJECT_SETTINGS: {
      resolution: { width: 1280, height: 720 },
      physics: { gravity: 1800 },
    },
    DEFAULT_LEVEL_SETTINGS: {
      gravity: null,
      music: "",
      cameraMode: "follow-player",
      ambientLight: 1,
    },
    DEFAULT_LEVEL_BOUNDS: {
      x: -960,
      y: -240,
      width: 1920,
      height: 960,
    },
    DEFAULT_CAMERA_START: {
      x: 0,
      y: 120,
    },
    DEFAULT_LAYERS: [
      { id: "layer-background", name: "Hintergrund", visible: true, locked: false, parallax: 0.4, order: 0 },
      { id: "layer-midground", name: "Mittelgrund", visible: true, locked: false, parallax: 0.75, order: 1 },
      { id: "layer-play", name: "Spielebene", visible: true, locked: false, parallax: 1, order: 2 },
      { id: "layer-foreground", name: "Vordergrund", visible: true, locked: false, parallax: 1.2, order: 3 },
    ],
    DEFAULT_OPEN_SECTIONS: {
      layers: true,
      info: false,
      properties: false,
      library: false,
      levelSettings: false,
      levelMeta: true,
      levelBounds: false,
      levelCamera: false,
      levelBackground: false,
      levelGeneral: false,
    },
    WORKSPACE_DEFINITIONS: [
      {
        id: "project",
        label: "Projekt",
        icon: "project",
        description: "Projektansicht folgt mit Kachel-Workflow in einer spaeteren Phase.",
        available: false,
      },
      {
        id: "level-editor",
        label: "Level Editor",
        icon: "level",
        description: "Aktiver Arbeitsbereich fuer Canvas, Ebenen und technische Geometrie.",
        available: true,
      },
      {
        id: "sprite-editor",
        label: "Sprite Editor",
        icon: "sprite",
        description: "Sprite-Sheets rastern, Animationen definieren und als Library-Item speichern.",
        available: true,
      },
    ],
    TOOL_DEFINITIONS: [
      {
        id: "select",
        label: "Markieren",
        icon: "select",
        shortcut: "M",
        description: "Waehlt Instanzen und technische Objekte aus.",
      },
      {
        id: "move",
        label: "Verschieben",
        icon: "move",
        shortcut: "V",
        description: "Bewegt die aktuelle Auswahl frei auf der Canvas.",
      },
      {
        id: "pan",
        label: "Pan",
        icon: "pan",
        shortcut: "H",
        description: "Verschiebt die Arbeitsansicht ohne Objektbearbeitung.",
      },
      {
        id: "zoom",
        label: "Zoom",
        icon: "zoom",
        shortcut: "",
        description: "Zoomt per Horizontal-Drag; Mausrad-Zoom bleibt an Ctrl gebunden.",
      },
      {
        id: "rectangle",
        label: "Rectangle",
        icon: "rectangle",
        shortcut: "R",
        description: "Erzeugt geometry-first Rechtecke fuer technische Zonen.",
      },
      {
        id: "polygon",
        label: "Polygon",
        icon: "polygon",
        shortcut: "P",
        description: "Setzt Punkte fuer freie technische Polygonzonen.",
      },
      {
        id: "playtest",
        label: "Playtest",
        icon: "play",
        shortcut: "Ctrl+Enter",
        description: "Playtest ist als naechster Ausbaupunkt vorbereitet.",
        available: false,
      },
    ],
    POINT_LOGIC_TYPES: ["spawn"],
    AREA_LOGIC_TYPES: ["solid", "hazard", "ladder", "one-way", "checkpoint"],
    LOGIC_LABELS: {
      spawn: "Spawn",
      solid: "Solid",
      hazard: "Hazard",
      ladder: "Leiter",
      "one-way": "One-Way",
      checkpoint: "Checkpoint",
    },
    LOGIC_STYLE_MAP: {
      spawn: { stroke: "#f0cb63", fill: "rgba(240,203,99,0.18)" },
      solid: { stroke: "#d67f69", fill: "rgba(214,127,105,0.28)" },
      hazard: { stroke: "#c75252", fill: "rgba(199,82,82,0.26)" },
      ladder: { stroke: "#57a173", fill: "rgba(87,161,115,0.24)" },
      "one-way": { stroke: "#6a95d0", fill: "rgba(106,149,208,0.22)" },
      checkpoint: { stroke: "#cfab58", fill: "rgba(207,171,88,0.24)" },
    },
    DEFAULT_LIBRARY_ITEMS: [
      {
        id: "graphic-tree-oak-01",
        type: "graphic",
        group: "Grafik",
        label: "Eiche",
        description: "Grosses statisches Deko-Objekt fuer Waldszenen und ruhige Mittelgruende.",
        tags: ["wald", "baum"],
        color: "#6f9a4f",
        size: { w: 160, h: 220 },
        capabilities: ["decorative", "static"],
      },
      {
        id: "graphic-rock-cluster-01",
        type: "graphic",
        group: "Grafik",
        label: "Felsgruppe",
        description: "Kompakte Steinformation fuer Vordergrund, Uebergaenge oder Wegkanten.",
        tags: ["fels", "boden"],
        color: "#807a74",
        size: { w: 184, h: 112 },
        capabilities: ["decorative", "grounding"],
      },
      {
        id: "sprite-hero-main",
        type: "sprite",
        group: "Sprites",
        label: "Held",
        description: "Animierter Player-Charakter mit Idle/Run/Jump als frueher Anker fuer den spaeteren Playtest.",
        tags: ["spieler", "character"],
        color: "#368fab",
        sheet: "assets/sprites/hero/hero.png",
        frameWidth: 192,
        frameHeight: 192,
        pivot: { x: 0.5, y: 1 },
        role: "character",
        defaultState: "idle",
        animations: {
          idle: { startFrame: 0, frameCount: 7, fps: 8, loop: true },
          run: { startFrame: 7, frameCount: 8, fps: 14, loop: true },
          jump: { startFrame: 15, frameCount: 8, fps: 12, loop: false },
        },
        capabilities: ["controllable", "run", "jump"],
      },
      {
        id: "sprite-guide-npc",
        type: "sprite",
        group: "Sprites",
        label: "Guide NPC",
        description: "Nicht spielbarer Charakter fuer Test-Dialoge und Wegfuehrung.",
        tags: ["npc", "dialog"],
        color: "#ca8b44",
        size: { w: 44, h: 84 },
        pivot: { x: 0.5, y: 1 },
        role: "character",
        defaultState: "idle",
        capabilities: ["dialog", "path"],
      },
      {
        id: "sprite-torch-01",
        type: "sprite",
        group: "Sprites",
        label: "Fackel",
        description: "Einfacher animierter Marker fuer Lichtstimmung und Rhythmus im Level.",
        tags: ["licht", "effekt"],
        color: "#d67d39",
        size: { w: 54, h: 120 },
        pivot: { x: 0.5, y: 1 },
        role: "effect",
        defaultState: "idle",
        capabilities: ["looping", "light-source"],
      },
    ],
  };
})();
