(() => {
  "use strict";

  window.LucidEditor = window.LucidEditor || {};
  window.LucidEditor.config = {
    PROJECT_SCHEMA_VERSION: 1,
    GRID_SIZE: 64,
    CAMERA_LIMITS: { minZoom: 0.25, maxZoom: 3.5 },
    DEFAULT_LAYERS: [
      { id: "layer-background", name: "Hintergrund", type: "background", parallax: 0.35, visible: true, locked: false },
      { id: "layer-midground", name: "Mittelgrund", type: "midground", parallax: 0.7, visible: true, locked: false },
      { id: "layer-play", name: "Spielebene", type: "play", parallax: 1, visible: true, locked: false },
      { id: "layer-foreground", name: "Vordergrund", type: "foreground", parallax: 1.25, visible: true, locked: false },
    ],
    DEFAULT_OPEN_SECTIONS: {
      selection: true,
      library: true,
      project: true,
      planning: false,
    },
    DEFAULT_LIBRARY_ITEMS: [
  {
    id: "tree-oak-01",
    label: "Eiche",
    category: "Grafik",
    kind: "visual",
    color: "#6f9a4f",
    size: { w: 160, h: 220 },
    description: "Statisches Deko-Objekt fuer mehrfach platzierte Baeume.",
    capabilities: ["render.image"],
    defaultProperties: { collidable: false, animated: false },
  },
  {
    id: "rock-cluster-01",
    label: "Felsgruppe",
    category: "Grafik",
    kind: "visual",
    color: "#7f7d78",
    size: { w: 180, h: 110 },
    description: "Grafisches Element fuer Vorder- oder Mittelgrund.",
    capabilities: ["render.image"],
    defaultProperties: { collidable: false, animated: false },
  },
  {
    id: "hero-main",
    label: "Main Character",
    category: "Akteure",
    kind: "actor",
    color: "#2e90a5",
    size: { w: 48, h: 92 },
    description: "Sprite-Figur mit Lauf-, Sprung- und Idle-Zustaenden.",
    capabilities: ["render.spriteAnimation", "movement.player", "stateMachine"],
    defaultProperties: { collidable: true, animated: true, controllable: true },
  },
  {
    id: "npc-guide",
    label: "Guide NPC",
    category: "Akteure",
    kind: "actor",
    color: "#c5873b",
    size: { w: 44, h: 84 },
    description: "Nicht spielbarer Charakter fuer Dialoge und Hilfen.",
    capabilities: ["render.spriteAnimation", "dialog.trigger", "behavior.path"],
    defaultProperties: { collidable: true, animated: true },
  },
  {
    id: "ladder-volume",
    label: "Leiterbereich",
    category: "Gameplay",
    kind: "collision",
    color: "#4e9460",
    size: { w: 80, h: 220 },
    description: "Technisches Volumen fuer Klettern.",
    capabilities: ["collision.ladder"],
    defaultProperties: { collidable: false, climbable: true, invisibleInGame: true },
  },
  {
    id: "solid-block",
    label: "Solid Block",
    category: "Gameplay",
    kind: "collision",
    color: "#b05b49",
    size: { w: 180, h: 80 },
    description: "Basiselement fuer Boden, Waende oder Podeste.",
    capabilities: ["collision.solid"],
    defaultProperties: { collidable: true, invisibleInGame: true },
  },
  {
    id: "trigger-checkpoint",
    label: "Checkpoint Trigger",
    category: "Trigger",
    kind: "trigger",
    color: "#d1a33c",
    size: { w: 120, h: 140 },
    description: "Unsichtbarer Trigger zum Aktualisieren des Respawn-Punkts.",
    capabilities: ["trigger.enter", "gameplay.checkpoint"],
    defaultProperties: { collidable: false, oneShot: false, invisibleInGame: true },
  },
  {
    id: "trigger-camera-zone",
    label: "Kamera-Zone",
    category: "Trigger",
    kind: "trigger",
    color: "#9171bf",
    size: { w: 220, h: 160 },
    description: "Steuert spaetere Kamerawechsel oder Fokuszonen.",
    capabilities: ["trigger.enter", "camera.override"],
    defaultProperties: { collidable: false, invisibleInGame: true },
  },
  {
    id: "torch-animated",
    label: "Fackel",
    category: "Effekte",
    kind: "animated",
    color: "#dd7432",
    size: { w: 54, h: 120 },
    description: "Animiertes Deko-Objekt fuer Licht und Atmosphaere.",
    capabilities: ["render.spriteAnimation", "fx.light"],
    defaultProperties: { collidable: false, animated: true, loops: true },
  },
  {
    id: "jump-pad",
    label: "Jump Pad",
    category: "Gameplay",
    kind: "logic",
    color: "#26867c",
    size: { w: 96, h: 48 },
    description: "Aktives Gameplay-Element fuer definierte Sprungimpulse.",
    capabilities: ["trigger.contact", "gameplay.launch"],
    defaultProperties: { collidable: true, animated: false, power: 1 },
  },
    ],
  };
})();
